# Generated by Django 2.0.5 on 2018-07-19 07:44

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_auto_20180717_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=50, verbose_name='级别名称')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='级别描述')),
                ('alias', models.CharField(blank=True, max_length=50, null=True, verbose_name='别名')),
            ],
            options={
                'verbose_name': '行政级别',
                'verbose_name_plural': '行政级别',
                'db_table': 'administrative_level',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
            ],
            options={
                'verbose_name': '市',
                'verbose_name_plural': '市',
                'proxy': True,
                'indexes': [],
            },
            bases=('area.area',),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
            ],
            options={
                'verbose_name': '省',
                'verbose_name_plural': '省',
                'proxy': True,
                'indexes': [],
            },
            bases=('area.area',),
        ),
        migrations.AddField(
            model_name='area',
            name='alias',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='别名'),
        ),
        migrations.AddField(
            model_name='area',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='area',
            name='parent_area',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='area.Area', verbose_name='上级区域'),
        ),
        migrations.AddField(
            model_name='area',
            name='administrative_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='area.AdministrativeLevel', verbose_name='行政级别'),
        ),
    ]
