# Generated by Django 2.0.5 on 2018-07-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_auto_20180719_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
            ],
            options={
                'verbose_name': '区/县',
                'verbose_name_plural': '区/县',
                'proxy': True,
                'indexes': [],
            },
            bases=('area.area',),
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '省/市/区(县)', 'verbose_name_plural': '省/市/区(县)'},
        ),
        migrations.AddField(
            model_name='area',
            name='area_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='电话区号'),
        ),
        migrations.AddField(
            model_name='area',
            name='postcode',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='area',
            name='alias',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='别名/简称'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='名称(全称)'),
        ),
    ]
