# Generated by Django 2.1.5 on 2019-01-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_auto_20190116_0749'),
        ('area', '0005_auto_20180719_0812'),
    ]

    operations = [
    ]
