# Generated by Django 2.1.5 on 2019-01-16 08:29

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0006_merge_20190116_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='administrative_level',
            new_name='common_level',
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='名称(全称)'),
        ),
        migrations.AlterField(
            model_name='area',
            name='parent_area',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='area.Area', verbose_name='上级区域'),
        ),
    ]
